### ISSUE TITLE
C++ error during install

### ISSUE THREAD

**Issue by fiddyschmitt** [daguej/node-console-title#1]
Hi,

When I install console-title using the following command, I get a c++ error. Any help would be appreciated.

`npm install console-title`

Thanks,
Fidel

I have VS2015 Community and added the 'Common Tools' to it. From an Admin console I then used:
```
npm install --global --production windows-build-tools
npm config set msvs_version 2015
```
but still no luck.

![cpp_error_message](https://cloud.githubusercontent.com/assets/15338956/26549997/151714dc-44bf-11e7-83bb-b382c4823108.png)

**Comment by daguej** [comment]
Aplogies for not responding earlier; this was fixed last June in v1.1 by removing the native dependency entirely.  See #2 for discussion.
