### ISSUE TITLE
Defunct / Obsolete

### ISSUE THREAD

**Issue by entozoon** [daguej/node-console-title#2]
Doesn't work with recent versions of Node and is obsolete, as you can simply do:
`process.title = "My App";`

(Not a criticism of this module, but just to help those googling their way here, as I did)

**Comment by adamsoutar** [comment]
For me on macOS with node v10.15.3, this is not correct. Not sure if @entozoon was only testing on Windows, but when I tested the two methods of changing title, they produced different effects:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/26578100/56133601-b516c180-5f84-11e9-9c2d-b73fde770490.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/26578100/56133620-ba740c00-5f84-11e9-9d16-48be29c0df2f.png">

Also, "doesn't work with recent versions of node"? Behind the scenes, it's just a call to process.stdout.write , not really sure how a node update could break it.

This issue is quite old, but people may still be coming across it during searches.

**Comment by daguej** [comment]
I believe that when @entozoon said it doesn't work with recent versions of node, he was referring to this module's [old native dependency for Windows](https://github.com/daguej/node-windows-console-title) that no longer builds on modern versions of node (it was written before [nan](https://www.npmjs.com/package/nan) existed).

He did correctly point out that the native module was no longer necessary as setting `process.title` does the exact same thing *on Windows*, so I updated this module to simply set `process.title` and removed the native dependency.

None of this changes what happens on Unixy systems; they have always required the ANSI escape sequences to change the title seen in a terminal emulator.  [The node docs allude to this](https://nodejs.org/docs/latest-v10.x/api/process.html#process_process_title):

> The `process.title` property returns the current process title (i.e. returns the current value of `ps`). Assigning a new value to `process.title` modifies the current value of `ps`.
>
> When a new value is assigned, different platforms will impose different maximum length restrictions on the title. Usually such restrictions are quite limited. For instance, on Linux and macOS, process.title is limited to the size of the binary name plus the length of the command line arguments because setting the process.title overwrites the argv memory of the process.

In truth, the behavior of node's `process.title` setter is surprisingly inconsistent.  Under the hood, it calls the libuv function [`uv_set_process_title`](http://docs.libuv.org/en/v1.x/misc.html#c.uv_set_process_title), which:

- On Linux, calls [`prctl(2)`](http://man7.org/linux/man-pages/man2/prctl.2.html) with `PR_SET_NAME`, which "sets the name of the calling thread".  This changes what `ps` shows as the process name.
- On OS X, it overwrites the process `argv` (to update what `ps` shows) and does [a bunch of undocumented Apple-specific stuff](https://github.com/libuv/libuv/blob/f4feea331a54e2b1a1cd432e04ea83d32cfd6c5c/src/unix/darwin-proctitle.c#L80-L177) to update what the Activity Monitor GUI shows.
- On Windows, there is no facility to change the name of a running process (Task Manager will *only* show the name of the executable file on disk), so it [simply calls `SetConsoleTitleW`](https://github.com/libuv/libuv/blob/2a9d626b4cba402528bdc9ab818eeb2690f7e79c/src/win/util.c#L387), which is a very different thing.  It is [documented](https://docs.microsoft.com/en-us/windows/console/setconsoletitle) as a way to change "the string to be displayed in the title bar of the console window."

The unix standard way of changing a terminal's window title is to issue a ANSI OSC sequence, which is what this module does.  This is a different thing than changing the process name.

So... all of that to say: no, this module is not actually obsolete for its purpose.  It is necessary if you want to change the title of the console window in a cross-platform way.

**Comment by entozoon** [comment]
I approve of all of these messages! Thanks for the replies.

Had no idea it was _that_ inconsistent, pretty shocking :(
Not being able to set the running process name in Windows is the bane of my life lol.
